import { z } from "zod";
export default z.object({
  SLACK_XOXB: z.string(),
  SLACK_XOXC: z.string(),
  SLACK_XOXD: z.string(),
  AIRTABLE_KEY: z.string(),
  BASE_ID: z.string(),
  API_KEY: z.string(),
  APP_TOKEN: z.string().optional(),
  SLACK_SIGNING_SECRET: z.string(),
  LOOPS_ID: z.string(),
  LOOPS_API_KEY: z.string(),
  JR_BASE_ID: z.string(),
  SLACK_XOXP: z.string(),
  UPTIME_URL_THING: z.string(),
  DOMAIN_OF_HOST: z.string(),
  GARDENS_URL: z.string().optional(),
  BANNED_USERS: z.string(),
  PG_CONNECTION_STRING: z.string(),
  PG_CONNECTION_STRING_SOM: z.string(),
  SOM_COOKIE: z.string(),
});
